### ISSUE TITLE
Protect voter identity though each ballots

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-dojo/votbot#3]
WIP in https://github.com/epfl-dojo/votbot/blob/master/main.go#L117 ; we get the salt but we need an input formal to each ballot.

**Comment by gcmalloc** [comment]
Isn't that already the case ?
We take hash(salt+userID), see https://github.com/epfl-dojo/votbot/blob/master/main.go#L148.

**Comment by ponsfrilus** [comment]
It wasn't in https://github.com/epfl-dojo/votbot/commit/80573ad5477da87ea85796cc330ead0eab930ce5#diff-7ddfb3e035b42cd70649cc33393fe32cR116
So it's fixed :)
